### ISSUE TITLE
Test Epic Issue Q3

### ISSUE THREAD

**Issue by ewferg** [NASA-AMMOS/aerie-pmc#1]
```[tasklist]
### Extended Meta for Records
- [ ] https://github.com/NASA-AMMOS/aerie/issues/950
- [ ] https://github.com/NASA-AMMOS/aerie/issues/928
- [ ] https://github.com/NASA-AMMOS/aerie/issues/934
```
